apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "infra-health-checker.fullname" . }}
  labels:
    {{- include "infra-health-checker.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "infra-health-checker.labels" . | nindent 12 }}
        spec:
          restartPolicy: {{ .Values.restartPolicy }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              volumeMounts:
                - name: config
                  mountPath: /app/config.yml
                  subPath: config.yml
                - name: reports
                  mountPath: /app/reports
          volumes:
            - name: config
              configMap:
                name: {{ include "infra-health-checker.fullname" . }}-config
            - name: reports
              emptyDir: {}