image:
  repository: ghcr.io/shanks69000/infra-health-checker
  tag: latest
  pullPolicy: IfNotPresent

schedule: "0 */6 * * *"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

config:
  checks:
    http:
      - name: GitHub
        url: https://github.com
        expected_status: 200
        timeout: 10
    tls:
      - name: GitHub TLS
        host: github.com
        port: 443
        warn_days: 30
    tcp:
      - name: GitHub SSH
        host: github.com
        port: 22
        timeout: 5
    dns:
      - name: GitHub DNS
        domain: github.com
        nameserver: 8.8.8.8

restartPolicy: OnFailure
successfulJobsHistoryLimit: 3
failedJobsHistoryLimit: 3
concurrencyPolicy: Forbid